sudo: required

language: python
python: "3.5"

services:
  - docker

env:
  - PIPENV_VENV_IN_PROJECT=1
  - PIPENV_IGNORE_VIRTUALENVS=1

before_install:
  - docker run --name ontology-orm-psql
      -p 5433:5433
      -e POSTGRES_DB=ontology-db
      -e POSTGRES_PASSWORD=ONTOLOGY-DB
      -d postgres

install:
  - cd test-generator-api
  - pip install pipenv
  - pipenv install --three

script:
  - pipenv run python -c 'from ontology_db.ontology_parser import parse_ontology; parse_ontology()'
  - pipenv run python -m pytest -v
