sudo: false
language: python
python:   
  - "3.6"

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres

install:
  - pip install pipenv
  - pipenv install --three

script:
  - pipenv run python -c "from api.ontology_db.ontology_parser import parse_ontology; parse_ontology()"
  - pipenv run python -m pytest -v
  - pipenv run python -m pytest --cov=./

after_success:
  - pipenv run codecov
