sudo: required

language: python
python: 
    - "3.5"

addons:
    apt:
      update: true

services:
  - docker

before_install:
  - docker run --name ontology-orm-psql
      -p 5433:5433
      -e POSTGRES_DB=ontology-db
      -e POSTGRES_PASSWORD=ONTOLOGY-DB
      -d postgres

install:
  - pip install pipenv

script:
  - pipenv install --dev --three
  - pipenv shell python -c 'from ontology_db.ontology_parser import parse_ontology; parse_ontology()'
  - python -m pytest -v
  - exit
